# Generated by Django 3.2.7 on 2021-10-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='e-mail verificado'),
        ),
        migrations.AddField(
            model_name='user',
            name='verify_email_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='último envío de correo de verificación'),
        ),
    ]
