# Generated by Django 2.1.7 on 2019-09-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeofferanswer',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='La respuesta aparece en la oferta para la que fue creada.', verbose_name='es visible'),
        ),
        migrations.AlterField(
            model_name='tradeofferanswer',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='El usuario ha completado su parte.', verbose_name='proceso completado'),
        ),
    ]
