# Generated by Django 2.1.7 on 2019-09-04 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_answer_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeoffer',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.TradePeriod', verbose_name='periodo'),
        ),
        migrations.AlterField(
            model_name='tradeoffer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AlterField(
            model_name='tradeofferanswer',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='trading.TradeOffer', verbose_name='oferta'),
        ),
        migrations.AlterField(
            model_name='tradeofferanswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AlterField(
            model_name='tradeofferline',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='trading.TradeOffer', verbose_name='oferta'),
        ),
        migrations.AlterField(
            model_name='tradeofferline',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year', to='heart.Year', verbose_name='año'),
        ),
    ]
