# Generated by Django 3.2.7 on 2021-09-23 11:11

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_removed_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeofferline',
            name='completed',
            field=models.CharField(blank=True, default='', max_length=64, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message=None)], verbose_name='intercambios completados'),
        ),
        migrations.AlterField(
            model_name='tradeofferline',
            name='started',
            field=models.CharField(blank=True, default='', max_length=64, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message=None)], verbose_name='intercambios iniciados'),
        ),
    ]
