# Generated by Django 2.1.7 on 2019-09-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_relations_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeoffer',
            name='description',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='descripción'),
        ),
    ]
