# Generated by Django 3.2.7 on 2021-11-06 19:22

import functools

import django.db.models.deletion
from django.conf import settings
from django.db import (
    migrations,
    models,
)

import houses.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('heart', '0022_activity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='nombre')),
                ('logo', models.ImageField(upload_to=functools.partial(houses.models.house_logo_path, *('houses/logos/',), **{}), verbose_name='logo')),
                ('plain_logo', models.ImageField(help_text='Se utilizará como fondo en los perfiles', upload_to=functools.partial(houses.models.house_logo_path, *('houses/plain-logos/',), **{}), verbose_name='logo plano')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='puntos')),
                ('default_rank', models.CharField(max_length=64, verbose_name='rango para nuevos miembros')),
                ('managers', models.ManyToManyField(related_name='house_managers', to=settings.AUTH_USER_MODEL, verbose_name='gestores')),
            ],
            options={
                'verbose_name': 'casa',
            },
        ),
        migrations.CreateModel(
            name='SelectorOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='respuesta')),
            ],
            options={
                'verbose_name': 'opción de pregunta',
                'verbose_name_plural': 'opciones de pregunta',
            },
        ),
        migrations.CreateModel(
            name='SelectorQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='pregunta')),
                ('category', models.CharField(max_length=120, verbose_name='categoría')),
            ],
            options={
                'verbose_name': 'pregunta del seleccionador',
                'verbose_name_plural': 'preguntas del seleccionador',
            },
        ),
        migrations.CreateModel(
            name='SelectorResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='selector_result', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'resultado del seleccionador',
                'verbose_name_plural': 'resultados del seleccionador',
            },
        ),
        migrations.CreateModel(
            name='SelectorResultPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(verbose_name='puntos')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.house', verbose_name='casa')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='houses.selectorresult', verbose_name='resultado')),
            ],
            options={
                'verbose_name': 'puntos de resultado',
                'verbose_name_plural': 'puntos de resultado',
            },
        ),
        migrations.CreateModel(
            name='SelectorOptionPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(verbose_name='puntos')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options_points', to='houses.house', verbose_name='casa')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='houses.selectoroption', verbose_name='opción')),
            ],
            options={
                'verbose_name': 'puntos de opción',
                'verbose_name_plural': 'puntos de opción',
            },
        ),
        migrations.AddField(
            model_name='selectoroption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='houses.selectorquestion', verbose_name='pregunta'),
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(verbose_name='puntos')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_points_transactions', to='heart.activity', verbose_name='actividad')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='houses.house', verbose_name='casa')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='house_points', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'transacción de puntos',
                'verbose_name_plural': 'transacciones de puntos',
                'permissions': (('can_give_points', 'Puede dar puntos a una casa'),),
            },
        ),
        migrations.CreateModel(
            name='HouseProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, verbose_name='puntos')),
                ('rank', models.CharField(max_length=64, verbose_name='rango')),
                ('nickname', models.CharField(blank=True, default='', max_length=64, verbose_name='apodo')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='houses.house', verbose_name='casa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='house_profile', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'perfil de casa',
                'verbose_name_plural': 'perfiles de casa',
            },
        ),
    ]
