# Generated by Django 2.1.13 on 2020-04-18 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import meta.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('heart', '0016_meeting_documents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000, verbose_name='texto')),
                ('is_official', models.BooleanField(default=False, verbose_name='es un comentario oficial')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='es un comentario anónimo')),
                ('reputation', models.IntegerField(default=0, verbose_name='reputación')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
            ],
            options={
                'verbose_name': 'comentario',
            },
        ),
        migrations.CreateModel(
            name='CommentVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_upvote', models.BooleanField(default=True, verbose_name='es voto positivo')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='feedback.Comment', verbose_name='comentario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_votes', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'voto',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='nombre')),
                ('slug', models.SlugField(max_length=200, verbose_name='slug')),
                ('description', models.TextField(max_length=2000, verbose_name='descripción')),
                ('is_public', models.BooleanField(default=True, verbose_name='permitir acceso al tema')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('documents', models.ManyToManyField(blank=True, to='heart.DocumentMedia', verbose_name='documentos relacionados')),
                ('meetings', models.ManyToManyField(blank=True, to='heart.Meeting', verbose_name='asambleas relacionadas')),
                ('official_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='official_position', to='feedback.Comment', verbose_name='postura oficial')),
            ],
            options={
                'verbose_name': 'tema',
                'ordering': ('-updated',),
            },
            bases=(meta.models.ModelMeta, models.Model),
        ),
        migrations.AddField(
            model_name='comment',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feedback.Topic', verbose_name='tema'),
        ),
    ]
