# Generated by Django 2.1.13 on 2020-04-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created',), 'verbose_name': 'comentario'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='reputation',
        ),
        migrations.AddField(
            model_name='comment',
            name='is_point',
            field=models.BooleanField(default=False, verbose_name='es un punto de debate'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=5000, verbose_name='texto'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.TextField(max_length=10000, verbose_name='descripción'),
        ),
    ]
