# Generated by Django 2.1.7 on 2019-03-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('content', models.TextField(max_length=5000, verbose_name='content')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
