# Generated by Django 2.1.7 on 2019-07-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('slug', models.SlugField(max_length=200, primary_key=True, serialize=False, verbose_name='slug')),
                ('content', models.TextField(max_length=5000, verbose_name='content')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
