# Generated by Django 2.1.7 on 2019-07-30 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False, verbose_name='código')),
                ('name', models.CharField(max_length=64, verbose_name='nombre')),
                ('acronym', models.CharField(max_length=6, verbose_name='siglas')),
                ('quarter', models.IntegerField(choices=[(1, 'Primer cuatrimestre'), (2, 'Segundo cuatrimestre')], default=1, verbose_name='cuatrimestre')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='año')),
                ('groups', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='número de grupos')),
                ('subgroups', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='subgrupos por grupo')),
            ],
            options={
                'verbose_name': 'asignatura',
            },
        ),
    ]
