# Generated by Django 2.1.7 on 2019-08-12 18:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='nombre de la sala')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='código de la sala')),
                ('members', models.CharField(blank=True, default='', max_length=128, verbose_name='miembros en la sala')),
            ],
            options={
                'verbose_name': 'sala',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False, verbose_name='código')),
                ('name', models.CharField(max_length=64, verbose_name='nombre')),
                ('acronym', models.CharField(max_length=6, verbose_name='siglas')),
                ('quarter', models.IntegerField(choices=[(1, 'Primer cuatrimestre'), (2, 'Segundo cuatrimestre')], default=1, verbose_name='cuatrimestre')),
            ],
            options={
                'verbose_name': 'asignatura',
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='año')),
                ('groups', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='número de grupos')),
                ('subgroups', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='número de subgrupos')),
            ],
            options={
                'verbose_name': 'año',
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='heart.Year', verbose_name='año'),
        ),
    ]
