# Generated by Django 2.1.7 on 2019-09-13 16:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('heart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='nombre')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='número de grupo')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='año')),
                ('subgroups', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='número de subgrupos')),
                ('telegram_group', models.CharField(blank=True, default='', max_length=64, verbose_name='grupo de telegram')),
                ('telegram_group_link', models.CharField(blank=True, default='', max_length=64, verbose_name='enlace al grupo de telegram')),
                ('delegate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delegate_group', to=settings.AUTH_USER_MODEL, verbose_name='delegado')),
                ('subdelegate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subdelegate_group', to=settings.AUTH_USER_MODEL, verbose_name='subdelegado')),
            ],
            options={
                'verbose_name': 'grupo',
                'permissions': [('can_link_group', 'Puede vincular un grupo de Telegram con un grupo de alumnos')],
            },
        ),
    ]
