# Generated by Django 2.1.7 on 2019-09-21 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0003_room_members_m2m'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'permissions': [('can_change_room_state', 'Puede cambiar el estado de una sala')], 'verbose_name': 'sala'},
        ),
    ]
