# Generated by Django 2.1.7 on 2019-10-05 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0004_room_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='members',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
