# Generated by Django 2.1.13 on 2019-10-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0005_delete_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('file', models.FileField(upload_to='docs/', verbose_name='archivo')),
                ('hidden', models.BooleanField(default=False, help_text='Ocultar el archivo en las listas', verbose_name='oculto')),
            ],
            options={
                'verbose_name': 'documento',
            },
        ),
    ]
