# Generated by Django 2.1.13 on 2019-10-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0007_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='course',
            field=models.CharField(choices=[('GII', 'Grado en Ingeniería Informática'), ('MNTI', 'Máster en Nuevas Tecnologías de la Informática'), ('MBD', 'Máster en Big Data')], default='GII', max_length=6, verbose_name='estudios'),
        ),
        migrations.AlterField(
            model_name='group',
            name='year',
            field=models.IntegerField(verbose_name='año'),
        ),
    ]
