# Generated by Django 2.1.13 on 2019-10-26 09:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0008_group_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='absents',
            field=models.ManyToManyField(blank=True, related_name='meetings_absent', to=settings.AUTH_USER_MODEL, verbose_name='ausencias justificadas'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='meetings_attended', to=settings.AUTH_USER_MODEL, verbose_name='asistentes'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='minutes',
            field=models.FileField(blank=True, upload_to='meetings/', verbose_name='acta'),
        ),
    ]
