# Generated by Django 2.1.13 on 2019-11-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0010_groups_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentmedia',
            name='category',
            field=models.CharField(blank=True, default='', help_text='Los documentos con la misma categoría aparecerán agrupados juntos en la lista.', max_length=200, verbose_name='categoría'),
        ),
    ]
