# Generated by Django 2.1.13 on 2019-11-02 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0011_documentmedia_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='year',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
