# Generated by Django 2.1.13 on 2019-11-04 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('heart', '0012_remove_trading_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='nombre')),
                ('is_hidden', models.BooleanField(default=False, help_text='Ocultar los miembros de este colectivo en las vistas públicas del sitio web', verbose_name='ocultar grupo')),
                ('show_in_meetings', models.BooleanField(default=True, help_text='Mostrar los miembros de este colectivo en las listas de asistencia de las asambleas', verbose_name='mostrar en asambleas')),
            ],
            options={
                'verbose_name': 'grupo de gente importante',
                'verbose_name_plural': 'grupos de gente importante',
            },
        ),
        migrations.CreateModel(
            name='PeopleGroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=120, verbose_name='título')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heart.PeopleGroup', verbose_name='grupo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'grupo de gente importante',
                'verbose_name_plural': 'grupos de gente importante',
            },
        ),
        migrations.AddField(
            model_name='peoplegroup',
            name='members',
            field=models.ManyToManyField(through='heart.PeopleGroupMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
