# Generated by Django 2.1.13 on 2019-11-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0014_committee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peoplegroup',
            options={'ordering': ('order', 'name'), 'verbose_name': 'grupo de gente importante', 'verbose_name_plural': 'grupos de gente importante'},
        ),
        migrations.AlterModelOptions(
            name='peoplegroupmember',
            options={'ordering': ('order', 'user__first_name'), 'verbose_name': 'grupo de gente importante', 'verbose_name_plural': 'grupos de gente importante'},
        ),
        migrations.AddField(
            model_name='peoplegroup',
            name='order',
            field=models.IntegerField(default=1, help_text='Se ordena de forma creciente (menor número sale antes).', verbose_name='orden'),
        ),
        migrations.AddField(
            model_name='peoplegroupmember',
            name='order',
            field=models.IntegerField(default=1, help_text='Se ordena de forma creciente (menor número sale antes).', verbose_name='orden'),
        ),
    ]
