# Generated by Django 2.1.13 on 2020-09-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0016_meeting_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False, verbose_name='año')),
                ('course', models.CharField(choices=[('GII', 'Grado en Ingeniería Informática'), ('MNTI', 'Máster en Nuevas Tecnologías de la Informática'), ('MBD', 'Máster en Big Data')], default='GII', max_length=6, verbose_name='estudios')),
                ('telegram_group', models.CharField(blank=True, default='', max_length=64, verbose_name='grupo de telegram')),
                ('telegram_group_link', models.CharField(blank=True, default='', max_length=64, verbose_name='enlace al grupo de telegram')),
            ],
            options={
                'verbose_name': 'año',
                'ordering': ('year',),
            },
        ),
    ]
