# Generated by Django 2.1.13 on 2020-09-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0017_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_ordinary',
            field=models.BooleanField(default=True, verbose_name='es una asamblea ordinaria'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='minutes_approved',
            field=models.BooleanField(default=False, verbose_name='el acta se ha aprobado'),
        ),
    ]
