# Generated by Django 2.1.13 on 2020-11-09 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0018_meetings_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='delegate',
        ),
        migrations.RemoveField(
            model_name='group',
            name='subdelegate',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
