# Generated by Django 2.1.13 on 2020-11-09 18:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('heart', '0019_remove_year_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='identificador')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('is_master', models.BooleanField(default=False, verbose_name='es un máster')),
                ('order', models.IntegerField(default=0, help_text='Las titulaciones con mayor orden salen antes', verbose_name='orden')),
            ],
            options={
                'verbose_name': 'titulación',
                'verbose_name_plural': 'titulaciones',
                'ordering': ('-order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='nombre')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='número de grupo')),
                ('subgroups', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='número de subgrupos')),
                ('telegram_group', models.CharField(blank=True, default='', max_length=64, verbose_name='grupo de telegram')),
                ('telegram_group_link', models.CharField(blank=True, default='', max_length=64, verbose_name='enlace al grupo de telegram')),
                ('delegate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delegate_group', to=settings.AUTH_USER_MODEL, verbose_name='delegado')),
                ('subdelegate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subdelegate_group', to=settings.AUTH_USER_MODEL, verbose_name='subdelegado')),
            ],
            options={
                'verbose_name': 'grupo',
                'ordering': ('-year__degree__order', 'year__degree', 'year', 'number'),
                'permissions': [('can_link_group', 'Puede vincular un grupo de Telegram con un grupo de alumnos')],
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='año')),
                ('telegram_group', models.CharField(blank=True, default='', max_length=64, verbose_name='grupo de telegram')),
                ('telegram_group_link', models.CharField(blank=True, default='', max_length=64, verbose_name='enlace al grupo de telegram')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='years', to='heart.Degree', verbose_name='titulación')),
            ],
            options={
                'verbose_name': 'año',
                'ordering': ('-degree__order', 'degree', 'year'),
            },
        ),
        migrations.AddField(
            model_name='group',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='heart.Year', verbose_name='año'),
        ),
    ]
