# Generated by Django 3.2.7 on 2021-09-26 09:21

from django.db import (
    migrations,
    models,
)


def set_null_on_empty(apps, schema_editor):
    Group: models.Model = apps.get_model('heart', 'Group')
    Year: models.Model = apps.get_model('heart', 'Year')

    (
        Group
        .objects
        .filter(telegram_group='')
        .update(telegram_group=None)
    )
    (
        Group
        .objects
        .filter(telegram_group_link='')
        .update(telegram_group_link=None)
    )

    (
        Year
        .objects
        .filter(telegram_group='')
        .update(telegram_group=None)
    )
    (
        Year
        .objects
        .filter(telegram_group_link='')
        .update(telegram_group_link=None)
    )


def set_empty_on_null(apps, schema_editor):
    Group: models.Model = apps.get_model('heart', 'Group')
    Year: models.Model = apps.get_model('heart', 'Year')

    (
        Group
        .objects
        .filter(telegram_group=None)
        .update(telegram_group='')
    )
    (
        Group
        .objects
        .filter(telegram_group_link=None)
        .update(telegram_group_link='')
    )

    (
        Year
        .objects
        .filter(telegram_group=None)
        .update(telegram_group='')
    )
    (
        Year
        .objects
        .filter(telegram_group_link=None)
        .update(telegram_group_link='')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0020_degree_year_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='telegram_group',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='grupo de telegram'),
        ),
        migrations.AlterField(
            model_name='group',
            name='telegram_group_link',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='enlace al grupo de telegram'),
        ),
        migrations.AlterField(
            model_name='year',
            name='telegram_group',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='grupo de telegram'),
        ),
        migrations.AlterField(
            model_name='year',
            name='telegram_group_link',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='enlace al grupo de telegram'),
        ),
        migrations.RunPython(set_null_on_empty, set_null_on_empty),
    ]
