# Generated by Django 3.2.7 on 2021-10-23 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_telegram_group_null'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('heart', '0021_telegram_group_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='título')),
                ('description', models.TextField(verbose_name='descripción')),
                ('place', models.TextField(verbose_name='lugar')),
                ('start', models.DateTimeField(verbose_name='fecha de inicio')),
                ('end', models.DateTimeField(verbose_name='fecha de fin')),
                ('checkin_points', models.PositiveIntegerField(default=1, verbose_name='puntos por participar')),
                ('free_points', models.PositiveIntegerField(default=0, verbose_name='puntos de libre asignación')),
                ('attendees', models.ManyToManyField(blank=True, related_name='activities_attended', to=settings.AUTH_USER_MODEL, verbose_name='asistentes')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='clubs.club', verbose_name='club organizador')),
            ],
            options={
                'verbose_name': 'actividad',
                'verbose_name_plural': 'actividades',
            },
        ),
    ]
