# Generated by Django 2.1.7 on 2019-10-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_change_room_state', 'Puede cambiar el estado de una sala'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
