# Generated by Django 2.1.7 on 2019-10-07 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botpermissions',
            options={'default_permissions': (), 'managed': False, 'permissions': (('can_change_room_state', 'Puede cambiar el estado de una sala'), ('can_manage_elections', 'Puede gestionar operaciones del periodo de elecciones'))},
        ),
    ]
