# Generated by Django 2.1.13 on 2019-10-28 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_bot_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botpermissions',
            options={'default_permissions': (), 'managed': False, 'permissions': (('can_change_room_state', 'Puede cambiar el estado de una sala'), ('can_change_alt_room_state', 'Puede cambiar el estado de la sala alternativa'), ('can_manage_elections', 'Puede gestionar operaciones del periodo de elecciones'), ('can_manage_permissions', 'Puede gestionar permisos de usuarios'))},
        ),
    ]
