# Generated by Django 2.1.7 on 2019-09-21 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'permissions': [('can_link_club', 'Puede vincular un grupo de Telegram con un club')], 'verbose_name': 'club', 'verbose_name_plural': 'clubes'},
        ),
    ]
