# Generated by Django 2.1.13 on 2019-11-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_club_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='slug',
            field=models.SlugField(max_length=64, unique=True, verbose_name='slug'),
        ),
    ]
