# Generated by Django 3.2.7 on 2021-09-26 09:59

from django.db import (
    migrations,
    models,
)


def set_null_on_empty(apps, schema_editor):
    Club: models.Model = apps.get_model('clubs', 'Club')

    (
        Club
        .objects
        .filter(telegram_group='')
        .update(telegram_group=None)
    )
    (
        Club
        .objects
        .filter(telegram_group_link='')
        .update(telegram_group_link=None)
    )


def set_empty_on_null(apps, schema_editor):
    Club: models.Model = apps.get_model('clubs', 'Club')

    (
        Club
        .objects
        .filter(telegram_group=None)
        .update(telegram_group='')
    )
    (
        Club
        .objects
        .filter(telegram_group_link=None)
        .update(telegram_group_link='')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_club_slug_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='telegram_group',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='grupo de telegram'),
        ),
        migrations.AlterField(
            model_name='club',
            name='telegram_group_link',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='enlace al grupo de telegram'),
        ),
        migrations.RunPython(set_null_on_empty, set_null_on_empty),
    ]
