# Generated by Django 2.1.13 on 2020-10-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanalberto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(verbose_name='fecha'),
        ),
    ]
