# Generated by Django 2.1.13 on 2020-10-18 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sanalberto', '0002_event_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='título')),
                ('image', models.ImageField(upload_to='designs/', verbose_name='imagen pública')),
                ('source_file', models.FileField(upload_to='designs-sources/', verbose_name='fichero fuente')),
                ('is_approved', models.BooleanField(default=False, verbose_name='diseño aprobado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
            ],
            options={
                'verbose_name': 'diseño',
                'ordering': ('-created', 'title'),
            },
        ),
        migrations.AddField(
            model_name='event',
            name='design_register_end',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='fin de registro de diseños'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='design_register_start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='inicio de registro de diseños'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='selling_end',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='fin de venta de productos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='selling_start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='inicio de venta de productos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='design',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanalberto.Event', verbose_name='evento'),
        ),
        migrations.AddField(
            model_name='design',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='creador'),
        ),
        migrations.AddField(
            model_name='event',
            name='winner_design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_won', to='sanalberto.Design', verbose_name='diseño ganador'),
        ),
    ]
