# Generated by Django 2.1.13 on 2020-10-21 08:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sanalberto', '0003_designs'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='design_poll_end',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='fin de elección de diseños'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='design_poll_start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='inicio de elección de diseños'),
            preserve_default=False,
        ),
    ]
