# Generated by Django 2.1.13 on 2020-10-21 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sanalberto', '0004_event_poll_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='título')),
                ('slug', models.SlugField(max_length=140)),
                ('register_start', models.DateTimeField(verbose_name='inicio de registro')),
                ('register_end', models.DateTimeField(verbose_name='fin de registro')),
                ('voting_start', models.DateTimeField(verbose_name='inicio de votación')),
                ('voting_end', models.DateTimeField(verbose_name='fin de votación')),
            ],
            options={
                'verbose_name': 'encuesta',
            },
        ),
        migrations.CreateModel(
            name='PollDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='título')),
                ('image', models.ImageField(upload_to='designs/', verbose_name='imagen')),
                ('source_file', models.FileField(upload_to='designs-sources/', verbose_name='fichero fuente')),
                ('is_approved', models.BooleanField(default=False, verbose_name='diseño aprobado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='sanalberto.Poll', verbose_name='encuesta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='creador')),
            ],
            options={
                'verbose_name': 'diseño',
                'ordering': ('-created', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='coste')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='precio')),
                ('stock', models.IntegerField(verbose_name='stock')),
            ],
            options={
                'verbose_name': 'producto',
            },
        ),
        migrations.RemoveField(
            model_name='design',
            name='event',
        ),
        migrations.RemoveField(
            model_name='design',
            name='user',
        ),
        migrations.RemoveField(
            model_name='event',
            name='design_poll_end',
        ),
        migrations.RemoveField(
            model_name='event',
            name='design_poll_start',
        ),
        migrations.RemoveField(
            model_name='event',
            name='design_register_end',
        ),
        migrations.RemoveField(
            model_name='event',
            name='design_register_start',
        ),
        migrations.RemoveField(
            model_name='event',
            name='winner_design',
        ),
        migrations.DeleteModel(
            name='Design',
        ),
        migrations.AddField(
            model_name='poll',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='sanalberto.Event', verbose_name='evento'),
        ),
    ]
