# Generated by Django 2.1.13 on 2020-10-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanalberto', '0005_polls_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='polldesign',
            name='vector_file',
            field=models.FileField(default='', upload_to='designs-vectors/', verbose_name='fichero del vectorizado'),
            preserve_default=False,
        ),
    ]
