# Generated by Django 2.1.13 on 2020-11-10 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('heart', '0020_degree_year_group'),
        ('sanalberto', '0006_polldesign_vector_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False, verbose_name='pagado')),
                ('present', models.BooleanField(default=False, verbose_name='presentado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
            ],
            options={
                'verbose_name': 'inscripción',
                'verbose_name_plural': 'inscripciones',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='documents',
            field=models.ManyToManyField(to='heart.DocumentMedia', verbose_name='documentos'),
        ),
        migrations.AddField(
            model_name='activity',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='activities/', verbose_name='imagen 1'),
        ),
        migrations.AddField(
            model_name='activity',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='activities/', verbose_name='imagen 2'),
        ),
        migrations.AddField(
            model_name='activityregistration',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='sanalberto.Activity', verbose_name='actividad'),
        ),
        migrations.AddField(
            model_name='activityregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
    ]
