# Generated by Django 2.1.13 on 2020-11-11 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanalberto', '0007_activities_registrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='mostrar públicamente'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='documents',
            field=models.ManyToManyField(blank=True, to='heart.DocumentMedia', verbose_name='documentos'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='sanalberto.Event', verbose_name='evento'),
        ),
    ]
