# Generated by Django 2.1.13 on 2020-11-11 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanalberto', '0010_activityregistration_payment_error'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityregistration',
            old_name='paid',
            new_name='is_paid',
        ),
        migrations.RemoveField(
            model_name='activityregistration',
            name='present',
        ),
    ]
