# Generated by Django 2.1.13 on 2020-11-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanalberto', '0011_registrations_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='registration_price',
            field=models.IntegerField(default=100, help_text='El precio se debe indicar en céntimos de euro (100 para 1€)', verbose_name='precio de la inscripción'),
        ),
    ]
