# Generated by Django 3.2.7 on 2021-10-12 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sanalberto', '0012_activity_registration_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_first', to='sanalberto.polldesign', verbose_name='diseño prioridad 1')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='sanalberto.poll', verbose_name='encuesta')),
                ('second', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes_second', to='sanalberto.polldesign', verbose_name='diseño prioridad 2')),
                ('third', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes_third', to='sanalberto.polldesign', verbose_name='diseño prioridad 3')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designs_voted', to=settings.AUTH_USER_MODEL, verbose_name='votante')),
            ],
            options={
                'verbose_name': 'voto',
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
