# Generated by Django 3.2.7 on 2021-11-01 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import (
    migrations,
    models,
)


def set_activities_organisers(apps, schema_editor):
    Activity: models.Model = apps.get_model('sanalberto', 'Activity')

    for activity in Activity.objects.all().prefetch_related('club__managers', 'organiser'):
        if activity.organiser:
            activity.organisers.add(activity.organiser)

        if activity.club:
            activity.organisers.add(*activity.club.managers.all())


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0007_telegram_group_null'),
        ('sanalberto', '0015_alter_polldesign_voting_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='organisers',
            field=models.ManyToManyField(related_name='organised_sa_activities', to=settings.AUTH_USER_MODEL, verbose_name='organizadores'),
        ),
        migrations.AddField(
            model_name='activity',
            name='registration_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='cierre de inscripciones'),
        ),
        migrations.AddField(
            model_name='activityregistration',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='fecha de última actualización'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.club', verbose_name='club organizador'),
        ),
        migrations.AlterField(
            model_name='activityregistration',
            name='comments',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='comentarios'),
        ),
        migrations.RunPython(set_activities_organisers),
        migrations.RemoveField(
            model_name='activity',
            name='organiser',
        ),
    ]
